### ISSUE TITLE
REST Controllers

### ISSUE THREAD

**Issue by GeorgeZudikhin** [imoalim/TourPlanner#5]
User Story 4.4: As a backend developer, I want to implement the REST controllers for tours and logs, so the frontend can retrieve and send data to the backend.

- ## Tour
- tours are managed in a list, and can be created, modified, deleted (CRUD) 
- [x] Create
- [x] Get
- [x] Modify
- [x] Delete
- ## Tour logs
-  for every tour the user can create new tour logs of the accomplished tour statistics o multiple tour logs are assigned to one tour o a tour-log consists of date/time, comment, difficulty, total distance, total time, and rating taken on the tour 
- [x] Create
- [x] Get
- [x] Modify
- [x] Delete

**Comment by imoalim** [comment]
@GeorgeZudikhin please close if #11 is tested
